USE FOOD;
CALL addItem ("000001", "French Fries", "FROZEN", "lb");
CALL addItem ("000002", "Cheddar Cheese Slice", "REFRIGERATED", "lb");
CALL addItem ("000003", "Ketchup", "DRY FOOD", "gal");
CALL addItem ("000004", "Napkins", "PAPER GOODS", "each");
CALL addItem ("000005", "Mustard", "DRY FOOD", "gal");
CALL addItem ("000006", "Mayonnaise", "DRY FOOD", "gal");
CALL addItem ("000007", "Pickles", "DRY FOOD", "gal");
CALL addItem ("000008", "Burger Buns", "DRY FOOD", "each");
CALL addItem ("000009", "Ground Beef", "MEAT", "lb");
CALL addItem ("000010", "Chicken Breast", "MEAT", "lb");
CALL addItem ("000011", "Lettuce", "PRODUCE", "head");
CALL addItem ("000012", "Tomatoes", "PRODUCE", "lb");
CALL addItem ("000013", "Onions", "PRODUCE", "lb");
CALL addItem ("000014", "Paper Towels", "PAPER GOODS", "roll");
CALL addItem ("000015", "Foam Takeout Containers", "PAPER GOODS", "each" );
CALL addItem ("000016", "Mozzarella Cheese", "REFRIGERATED", "lb");
CALL addItem ("000017", "Bacon", "REFRIGERATED", "lb");
CALL addItem ("000018", "Frozen Chicken Nuggets", "FROZEN", "lb");
CALL addItem ("000019", "Hash Browns", "FROZEN", "lb");
CALL addItem ("000020", "BBQ Sauce", "DRY FOOD", "gal");

SELECT * FROM Item;
SELECT * FROM ItemInventoryData;