USE FOOD;
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS InventorySnapshotRecord;
DROP TABLE IF EXISTS InventorySnapshot;
DROP TABLE IF EXISTS InventoryTransaction;
DROP TABLE IF EXISTS PrepPlan;
DROP TABLE IF EXISTS Ingredient;
DROP TABLE IF EXISTS Recipe;
DROP TABLE IF EXISTS ProductInventory;
DROP TABLE IF EXISTS InvoiceLine;
DROP TABLE IF EXISTS Invoice;
DROP TABLE IF EXISTS Product;
DROP TABLE IF EXISTS Employee;
DROP TABLE IF EXISTS Item;
DROP TABLE IF EXISTS Vendor;
DROP TABLE IF EXISTS Category;
SET FOREIGN_KEY_CHECKS = 1;







